### PR TITLE
Social media website 

### PR DESCRIPTION
**Pull request by ozovalihasan**
Please review code for ruby on rails social media project. In this project we:

- Created ERD of the project
- Added pdf of ERD to docs folder

Hasan and Hillary

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the effort put in that milestone.
Please, a bit more effort to apply some suggested changes and move forward

1. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png), there should be a column keeping the profile image of the `User`

2. Please, `like/dislike` is not common as a table named. Kindly modify it.
In this table, `status` is it really needed ?

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by ozovalihasan** [comment]
Thanks, @maelfosso, for your feedback. We made the necessary changes.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next project.
- Happy coding!

**Comment by ozovalihasan** [comment]
Thanks, @rOluochKe, for your feedback.

**Pull request merged**
